-- P02
-- 8. Obter os títulos dos livros que renderam mais de 100 euros ao seu autor.
--    Ordenar o resultado por género e preço. 
SELECT LIVROS.TITULO, 0.3*sum(LIVROS.PRECO_TABELA*VENDAS.QUANTIDADE) AS "Rendimento"
FROM VENDAS, LIVROS
WHERE VENDAS.CODIGO_LIVRO = LIVROS.CODIGO_LIVRO
GROUP BY LIVROS.TITULO, LIVROS.GENERO, LIVROS.PRECO_TABELA
HAVING  0.3*sum(LIVROS.PRECO_TABELA*VENDAS.QUANTIDADE) > 100
ORDER BY LIVROS.GENERO, LIVROS.PRECO_TABELA;
